name: commit-with-another-repository

on:
  push:
    branches: [ "main", "test-workflow" ]

jobs:
  pull-target-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Cache problem list
#        uses: actions/cache@v3
#        with:
#          path: /problem
#          key: ${{ runner.os }}-problem-list
#          restore-keys: ${{ runner.os }}-problem-list

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: List pushed files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $changed_files; do
            echo "Content of $file:"
            cat $file
          done
      - name: Clone another repository
        run: |
          git clone https://github.com/anti-fragile-study/algorithm-study.git
          cd algorithm-study/
          
          ### Find wanted directory
          ls -d */
          username= ${ secrets.
          now=11
          branches=$(git branch -r)
          
          ### Has this week branch?
          echo "$branches" | { grep "origin/$username/week-$now" || true; }
