name: commit-with-another-repository

on:
  push:
    branches: [ "main", "test-workflow" ]

jobs:
  extract-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List pushed files
        id: find-target-problem
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $changed_files; do
            result=$(echo $file | { grep "README.md" || true; })
            if [[ -z $result ]];then
              file_name=$(printf $file | sed 's/"//g')
              echo "FILE_NAME=$file_name" >> $GITHUB_ENV
              printf "Content of $file_name:"
            fi 
          done
          echo ${{ env.FILE_NAME }}
      - name: Clone target repository
        run: git clone https://github.com/anti-fragile-study/algorithm-study.git
      - run: ls -al
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: run python script
        id: run-python-script
        run: python problem/parser.py $FILE_NAME
        env:
          FILE_NAME: ${{ env.FILE_NAME }}
      - name: test
        run: |
          test=$(cat problem/result.txt)
          week_number=$(echo $test | grep -oE 'week=[0-9]+' | sed 's/^week=//')
          type=$(echo $test | grep -oE 'type=[A-Z]+' | sed 's/^type=//')
          problem_number=$(echo $test | grep -oE 'number=[0-9]+' | sed 's/^number=//')
          problem_name=$(echo $test | grep -oE 'name=([^\n]+)' | sed 's/^name=//' | sed 's/...$//')
          language=$(echo $test | grep -oE 'language=[a-z]+' | sed 's/^language=//')
          echo $week_number
          echo $type
          echo $problem_name
          echo $language
          echo ${{ env.FILE_NAME }}
          
          cd algorithm-study
          username=protoseo
          branches=$(git branch -r)
          echo $branches
          target_branch="$branches" | { grep "origin/$username/week-$week_number" || true; }
          directory="week-$week_number/$username/$problem_name.$language"
          echo $target_branch
          echo "origin/$username/week-$week_number"
          if [[ -z $target_branch ]];then
            echo "create target branch" 
            git checkout -b "$username/week-$week_number"
            cat "../$FILE_NAME" >> $directory
            ls "week-$week_number/$username"
            cat $directory
          else
            echo "has target branch"
            git checkout -t "origin/$username/week-$week_number"
            git pull origin "$username/week-$week_number"
          fi
