name: commit-with-another-repository

on:
  push:
    branches: [ "main", "test-workflow" ]

jobs:
  extract-problem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List pushed files
        id: find-target-problem
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $changed_files; do
            result=$(echo $file | { grep "README.md" || true; })
            if [[ -z $result ]];then
              file_name=$(printf $file | sed 's/"//g')
              echo "FILE_NAME=$file_name" >> $GITHUB_ENV
              printf "Content of $file_name:"
              echo "file_directory=$(printf $file | sed 's/"//g')" >> $GITHUB_OUTPUT
            fi 
          done
          echo ${{ env.FILE_NAME }}
          echo ${{ steps.find-target-problem.file_directory}}
      - name: Clone another repository
        run: |
          git clone https://github.com/anti-fragile-study/algorithm-study.git
      - run: ls -al
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: run python script
        id: run-python-script
        run: python problem/parser.py $FILE_NAME
        env:
          FILE_NAME: ${{ env.FILE_NAME }}
      - name: get result
        run: |
          cat problem/result.txt
          echo ${{ steps.run-python-script.outputs.my_output }}
  pull-target-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Cache problem list
#        uses: actions/cache@v3
#        with:
#          path: /problem
#          key: ${{ runner.os }}-problem-list
#          restore-keys: ${{ runner.os }}-problem-list
      - name: List pushed files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for file in $changed_files; do
            result=$(echo $file | { grep "README.md" || true; })
            if [[ -z $result ]];then
              file_name=$(printf $file | sed 's/"//g')
              printf "Content of $file_name:"
              echo "file_name=$(printf $file | sed 's/"//g')" >> $GITHUB_OUTPUT
            fi 
          done
      - name: Clone another repository
        run: |
          git clone https://github.com/anti-fragile-study/algorithm-study.git
          cd algorithm-study/
          
          ### Find wanted directory
          IFS=$'\n'
          directories=$(ls -d */ | sort)
          last_dir=""
          for dir in $directories;do
            if [[ ${#dir} -eq 8 ]];then
              last_dir="$dir"
            fi
          done
  
          echo $last_dir
          cat $last_dir"problem.md"
            
          ### Settings
          username=protoseo
          now=11
          branches=$(git branch -r)
          
          ### Has this week branch?
          ### echo "$branches" | { grep "origin/$username/week-$now" || true; }
          target_branch="$branches" | { grep "origin/$username/week-$now" || true; }
          echo $target_branch
#          if [[ -z target_branch ]];then
#            git checkout -b "$username/week-$now"
#            echo $(git branch --show-current)
#          else
#            git pull origin "$username/week-$now"
  #          echo $(git branch --show-current)
#          fi
